### ISSUE TITLE
没达到演示的效果啊

### ISSUE THREAD

**Issue by zhangjingex** [fgkeepalive/AndroidKeepAlive#4]
https://github.com/fgkeepalive/AndroidKeepAlive/assets/45728042/9cfc2424-a920-4b86-bd16-e0a4eec22edf

**Comment by zhangjingex** [comment]
还是说其实是存活的，但是设置中没显示正在运行？但是演示中小米手机是显示的运行中

**Comment by fgkeepalive** [comment]
可以换个手机试试 这个不是100% 机型兼容的
